### ISSUE TITLE
Add the Netscape parser

### ISSUE THREAD

**Issue by vlnk** [team-chiru/sidemark-back#4]
- [x] Add the parser library for export
- [x] Add the import library (Stachemu)
- [x] Add associated endpoints
- [x] Add associated unit tests for import and export
    - [x] Refactor CRUD test
    - [x] Test serialization
    - [x] Test deserialization
    - [x] Test netscape parser
    - [x] Test tree creation
    - [x] Test tree fetching
- [x] Add the logic in order to fetch/add all imoprted/exported data
- [x] Update README for testing

**Comment by Tower450** [comment]
Added refactor CRUD test.

**Comment by vlnk** [comment]
Need to deleted the empty Menu folder during import and test the imported result on the sample object

**Comment by vlnk** [comment]
team-chiru/sidemark-back/import-tests merged on team-chiru/sidemark-back/dev
